### PR TITLE
Improvements to PR #246 (hiding the "Upload" tab)

### PR DESCRIPTION
**Pull request by dairiki**
Lying in bed last night, it came to me that a better way to implement the goals of PR #246 was simply to disable the ``upload``, ``upload-submit``, and ``add_file`` views on contexts for which ``File`` resources are not sdi-addable.  (PR #246 just hides the _Upload_ tab, the views are still accessible, even though invoking these views would not be appropriate.)

This PR adds a new _view predicate_ which checks the context to see whether a specific content type is sdi-addable.  This predicate is then used to protect the previously mentioned views.  (I'm not sure that the name of the predicate, ``sdi_addable``, is the best choice.  Suggestions welcome.)

I've also renamed the new function ``content_type_addable``, introduced in #246, to ``is_sdi_addable`` to more closely match the name of the view predicate.

### CODE REVIEW

**Comment by cguardia** [comment]
Hey, thanks for taking the time to improve this code. About the predicate name, how about `tab_addable_content`? That would be more in line with the current names for other management view predicates.

Other than that nit, this looks good to me.

**Comment by dairiki** [comment]
I’m not sure about the "tab_" in `tab_addable_content`.  The _Add_ UI element is a dropdown button, not a tab.  Maybe `sdi_addable_content`?  Or just `addable_content`?

While we are working out API naming nits: where should the `is_sdi_addable` predicate function be located?  I have initially put it in `substanced.folder.util`, but now I'm thinking a better location is one level up in `substanced.folder` (a la `substanced.property.is_propertied`, `substanced.catalog.is_catalogable`, and `substanced.workflow.is_workflowed`.)

**Comment by cguardia** [comment]
My thinking was that this is like a specialized case of the tab_condition predicate, but I see your point. My vote at this time would be for `addable_content`.

I agree that `substanced.folder` might be a better location for the predicate.

**Comment by cguardia** [comment]
Thanks!

**Comment by dairiki** [comment]
No problem.  Thank you!

**Pull request merged**
