### PR TITLE
add zh_CN translations

### PR DESCRIPTION
**Pull request by kerneltravel**
add translation of simplified chinese.

### CODE REVIEW

**Comment by kerneltravel** [comment]
All checks have failed ?

**Comment by tseaver** [comment]
@kerneltravel 

> All checks have failed ?

There is an issue with the recent changes to the `transaction` package, which used to require "native" strings for transaction notes (bytes on Python2, text on Python3), but now requires text (unicode on Python2).  So the Python 2.7 tests are failing.  It is not related to your pull request at all.

**Comment by domenkozar** [comment]
@kerneltravel I don't see Slovenian as being updated in this PR

**Comment by kerneltravel** [comment]
@domenkozar  yeah, I add zh_CN translations only. sorry for my incorrect commit message of git.

**Comment by kerneltravel** [comment]
How about this PR?

**Comment by cguardia** [comment]
Thanks!

**Pull request merged**
